// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Hzi8t5n3lEO5Tzv2YQMs8i5znd-jstE',
    appId: '1:657456061003:web:caf73444778037f83ccbce',
    messagingSenderId: '657456061003',
    projectId: 'task-management-app-b5f47',
    authDomain: 'task-management-app-b5f47.firebaseapp.com',
    storageBucket: 'task-management-app-b5f47.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoh2btl70CKJfEd7Rh2CidFxjwewkWzbA',
    appId: '1:657456061003:android:cc1a77e686e442d53ccbce',
    messagingSenderId: '657456061003',
    projectId: 'task-management-app-b5f47',
    storageBucket: 'task-management-app-b5f47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh_DgEe4Z31hiScNaYUO4ytcpce-ZwWTc',
    appId: '1:657456061003:ios:1e7e3aeb999ecdf13ccbce',
    messagingSenderId: '657456061003',
    projectId: 'task-management-app-b5f47',
    storageBucket: 'task-management-app-b5f47.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh_DgEe4Z31hiScNaYUO4ytcpce-ZwWTc',
    appId: '1:657456061003:ios:1e7e3aeb999ecdf13ccbce',
    messagingSenderId: '657456061003',
    projectId: 'task-management-app-b5f47',
    storageBucket: 'task-management-app-b5f47.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Hzi8t5n3lEO5Tzv2YQMs8i5znd-jstE',
    appId: '1:657456061003:web:1cc452b73f04d7483ccbce',
    messagingSenderId: '657456061003',
    projectId: 'task-management-app-b5f47',
    authDomain: 'task-management-app-b5f47.firebaseapp.com',
    storageBucket: 'task-management-app-b5f47.firebasestorage.app',
  );
}
